sudo: required
language: node_js
os:
    - windows
services: 
    - docker
before_install:
    - docker build -t abhishekv5055/docker-react -f Dockerfile.dev .
script:
    - docker run abhishekv5055/docker-react npm run test -- --coverage