language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services: 
    - docker
before_install:
    - docker build -t abhishekv5055/docker-react -f Dockerfile.dev .
script:
    - docker run abhishekv5055/docker-react npm run test -- --coverage